### ISSUE TITLE
Add option to choose Argon2 as password hash algorithm

### ISSUE THREAD

**Issue by TETYYS** [bytecurry/chloride#1]

**Comment by tmccombs** [comment]
That's a good suggestion. Any suggestions on what the API should look like?

**Comment by TETYYS** [comment]
Add an option in PwHashConfig?
or maybe wrap the thing in a class and add parameter in constructor

---
nice module dude but files where it's clearly seen that lots of functions have same arguments could use some class wrapping

**Comment by TETYYS** [comment]
very nice
